// User role constants — single source of truth.

export const ROLES = {
  STUDENT: 'Student',
  INSTRUCTOR: 'Instructor',
  ADMIN: 'Admin',
  SUPER_ADMIN: 'SuperAdmin',
};

export const LEARNER_ROLES = [ROLES.STUDENT, ROLES.INSTRUCTOR];

export const ROLE_HIERARCHY = {
  [ROLES.SUPER_ADMIN]: [ROLES.SUPER_ADMIN, ROLES.ADMIN, ROLES.INSTRUCTOR, ROLES.STUDENT],
  [ROLES.ADMIN]: [ROLES.ADMIN, ROLES.INSTRUCTOR, ROLES.STUDENT],
  [ROLES.INSTRUCTOR]: [ROLES.INSTRUCTOR, ROLES.STUDENT],
  [ROLES.STUDENT]: [ROLES.STUDENT],
};